In [1]:
##implementing hill cipher with given key and its inverse
import numpy as np

In [2]:
plaintext="code is ready"
dictionary={'a':0,'b':1,'c':2,'d':3,'e':4,'f':5,'g':6,'h':7,'i':8,'j':9,'k':10,'l':11,'m':12,'n':13,'o':14,'p':15,'q':16,
           'r':17,'s':18,'t':19,'u':20,'v':21,'w':22,'x':23,'y':24,'z':25}
print(dictionary['j'])
size=len(plaintext)
l=[]

9


In [3]:
for i in range(0,size):
    if(plaintext[i]!=' '):
        temp=dictionary.get(plaintext[i])
        l.append(temp)
l.append(dictionary.get('z'))
ll=[]
ll.append(l[0:4])
ll.append(l[4:8])
ll.append(l[8:12])
ptext=np.array(ll)
print(ptext)

[[ 2 14  3  4]
 [ 8 18 17  4]
 [ 0  3 24 25]]


In [9]:
key = [[9,7,11,13],[4,7,5,6],[2,21,14,9],[3,23,21,8]]
keytempinv=np.linalg.inv(key)
print(keytempinv*1973)
#keytempinv = [[2,15,22,3],[15,0,19,3],[9,9,3,11],[17,0,4,7]]

cipher=np.matmul(ptext,key)

for i in range(0,3):
    for j in range(0,4):
        cipher[i][j]=cipher[i][j]%26

print("the cipher text is:")
print(cipher)

decipher=np.matmul(cipher,keytempinv)

for i in range(0,3):
    for j in range(0,4):
        decipher[i][j]=decipher[i][j]%26
print("The plain text is:")
print(decipher)

[[-370. 1437. -716.  329.]
 [-253.  572.  -31.   17.]
 [ 181. -495.  -87.  175.]
 [ 391. -884.  586. -385.]]
the cipher text is:
[[14  7 10 13]
 [ 8  7  6  7]
 [ 5  8 18 18]]
The plain text is:
[[25.97060314  3.89254942 24.22959959  0.74505829]
 [25.53978713  3.21439432 24.80131779  0.56056766]
 [ 3.25494171 19.38013178  2.61226559 24.9868221 ]]
